var art = new Artplayer({
    container: '.artplayer-app',
    url: '',
    title: 'configuration',
    volume: 0,
    isLive: false,
    muted: false,
    autoplay: false,
    pip: false,
    autoSize: true,
    autoMini: false,
    screenshot: false,
    setting: false,
    loop: true,
    flip: false,
    rotate: false,
    playbackRate: false,
    aspectRatio: false,
    fullscreen: false,
    fullscreenWeb: false,
    subtitleOffset: false,
    miniProgressBar: false,
    localVideo: false,
    localSubtitle: false,
    mutex: true,
    backdrop: false,
    theme: '#28283A',
    lang: navigator.language.toLowerCase(),
    highlight: [
        {
            time: 60,
            text: 'One more chance',
        },
        {
            time: 120,
            text: '谁でもいいはずなのに',
        },
        {
            time: 180,
            text: '夏の想い出がまわる',
        },
        {
            time: 240,
            text: 'こんなとこにあるはずもないのに',
        },
        {
            time: 300,
            text: '终わり',
        },
    ],
});